-- ON SYSTEM
CREATE USER PDULEBA IDENTIFIED BY PDULEBA;
GRANT ALL PRIVILEGE TO PDULEBA;

-- ON PDULEBA
DROP TABLE PDULEBA.T_USERS;
DROP SEQUENCE PDULEBA.USERS_SEQ;

CREATE TABLE USERS (
  ID              	NUMBER(15),
  NAME            	VARCHAR2(100 CHAR) NOT NULL,
  PASSWORD_HASH     VARCHAR2(100 CHAR),
  CREATION_DATE	  	TIMESTAMP,
  CONSTRAINT NAME_UNIQUE UNIQUE (NAME),
  CONSTRAINT USER_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE USERS_SEQ START WITH     1 INCREMENT BY   1 NOCACHE NOCYCLE;
